name: Sincronizar ERP com Bagy

on:
  workflow_dispatch: # Permite executar manualmente
  schedule:
    - cron: '*/5 * * * *'  # Executa a cada 5 minutos (UTC)

jobs:
  sync-job:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências (se houver requirements.txt)
        run: |
          if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi

      - name: Executar sincronização
        run: python bagy_integration/sync_gestaoclick_to_bagy.py
